# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{googlecontacts}
  s.version = "0.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pieter Noordhuis"]
  s.date = %q{2011-01-02}
  s.description = %q{Google Contacts API implementation}
  s.email = %q{pcnoordhuis@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/google_contacts.rb",
    "lib/google_contacts/auth.rb",
    "lib/google_contacts/base.rb",
    "lib/google_contacts/contact.rb",
    "lib/google_contacts/group.rb",
    "lib/google_contacts/proxies/array.rb",
    "lib/google_contacts/proxies/emails.rb",
    "lib/google_contacts/proxies/hash.rb",
    "lib/google_contacts/proxies/tag.rb",
    "lib/google_contacts/wrapper.rb",
    "lib/googlecontacts.rb",
    "spec/assets/contacts_full.xml",
    "spec/assets/contacts_full_page1.xml",
    "spec/assets/contacts_full_page2.xml",
    "spec/assets/groups_full.xml",
    "spec/base_spec.rb",
    "spec/contact_spec.rb",
    "spec/group_spec.rb",
    "spec/proxies/array_spec.rb",
    "spec/proxies/emails_spec.rb",
    "spec/proxies/hash_spec.rb",
    "spec/proxies/tag_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/wrapper_spec.rb"
  ]
  s.homepage = %q{http://github.com/pietern/googlecontacts}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Contacts API on steroids}
  s.test_files = [
    "spec/base_spec.rb",
    "spec/contact_spec.rb",
    "spec/group_spec.rb",
    "spec/proxies/array_spec.rb",
    "spec/proxies/emails_spec.rb",
    "spec/proxies/hash_spec.rb",
    "spec/proxies/tag_spec.rb",
    "spec/spec_helper.rb",
    "spec/wrapper_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.3.6"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_dependency(%q<oauth>, [">= 0.3.6"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    s.add_dependency(%q<oauth>, [">= 0.3.6"])
  end
end

